"""Write the Windows version resource for TheChatPlace.exe (from GHManage's
``assets/make_version_info.py``).

Without it the built exe's Properties, Details tab is blank. The version
comes from ``thechatplace/__init__.py``, the one place it lives.

    python tools/make_version_info.py   # writes build/version_info.txt
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from thechatplace import __version__  # noqa: E402

TEMPLATE = """\
# Generated by tools/make_version_info.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup},
    prodvers={tup},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Kelly Ford'),
         StringStruct('FileDescription', 'The Chat Place, a home for your Claude Code chats'),
         StringStruct('FileVersion', '{version}'),
         StringStruct('InternalName', 'TheChatPlace'),
         StringStruct('LegalCopyright', 'Copyright (c) Kelly Ford. MIT License.'),
         StringStruct('OriginalFilename', 'TheChatPlace.exe'),
         StringStruct('ProductName', 'The Chat Place'),
         StringStruct('ProductVersion', '{version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def as_tuple(version: str):
    parts = [int(p) for p in re.findall(r"\d+", version)][:4]
    return tuple(parts + [0] * (4 - len(parts)))


def main() -> int:
    out = ROOT / "build" / "version_info.txt"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(TEMPLATE.format(tup=as_tuple(__version__), version=__version__),
                   encoding="utf-8")
    print(f"Wrote {out} (version {__version__})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
